### ISSUE TITLE
Erro NullPointerException

### ISSUE THREAD

**Issue by Gabitil** [steves-underwater-paradise/blinkload#14]
Exit:

The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot read the array length because "stitchResults" is null

Crash Log:
[crash-2024-12-08_12.10.19-client.txt](https://github.com/user-attachments/files/18052752/crash-2024-12-08_12.10.19-client.txt)

Minecraft: 1.20.1
Forge: 47.3.11
Mod version: 1.1.0

**Comment by CaoTrongThang** [comment]
I got the same

java.lang.NullPointerException: Cannot read the array length because "stitchResults" is null
	at knot//io.github.steveplays28.blinkload.client.cache.BlinkLoadCache.loadCachedData(BlinkLoadCache.java:108)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
